### ISSUE TITLE
Azure Storage provider fails to properly detect blob type

### ISSUE THREAD

**Issue by stewartadam** [Accelize/pycosio#2]
The call to `_head()` in [storage/azure_blob.py line 240](https://github.com/Accelize/pycosio/blob/70fa5e2444395a980aaa1b463ad5479043ba7930/pycosio/storage/azure_blob.py#L240) returns types in the format of `FooBlob` (e.g. `BlockBlob`), which causes a failure to lookup the blob type in as that dictionary is keyed by the lowercase blob type (e.g. `block`, `append`, `page`).

**Comment by stewartadam** [comment]
Super quick hack that fixed the issue for me: replace line 240 with `self._blob_type = self._head().get('blob_type', 'page').split('Blob')[0].lower()`

However it then proceeds to fail because unlike the AppendBlobService and PageBlobService classes, BlockBlobService has no `create_blob()` method.

**Comment by xlz-jgoutin** [comment]
Fixed in PR #5.
