### ISSUE TITLE
Downloads above 8MB fail

### ISSUE THREAD

**Issue by stewartadam** [Accelize/pycosio#25]
Testing using `shutil` (same as in #23), I've noticed files >8MB fail to download and are written with only a single 8MB chunk instead (exactly 8388608 bytes). All segments are downloaded, but they are not written to the output file.

**Comment by xlz-jgoutin** [comment]
Thanks for the report, should be fixed in ef8e7ad.

**Comment by xlz-jgoutin** [comment]
@stewartadam Is this issue fixed for you. I would like close it if OK.

**Comment by stewartadam** [comment]
Confirmed, fixed in 1.3.3 - thx!
