### ISSUE TITLE
Block blob uploads never have their blocks committed

### ISSUE THREAD

**Issue by stewartadam** [Accelize/pycosio#6]
1. `_close_writable()` had `if not self._blob_type`, which ended up actually only attempting to commit blocks when the block type was not block
2. `get_block_list()` does not seem to function as intended and always returns an empty list, even after several `put_block` calls (see https://github.com/Azure/azure-storage-python/issues/532).

**Comment by xlz-jgoutin** [comment]
Based on my tests, the blocks seem to be committed correctly in the new pycosio 1.3.0 (But I changed a lot of things since this issue was open).

@stewartadam Do not hesitate to review the 1.3.0 Azure support and report any issue with it.

**Comment by stewartadam** [comment]
Can confirm, this works as expected in master branch. Closing
